name: "Direktive Vision Add-on"
version: "0.1.0"
slug: "direktive-addon"
description: "Direktive's vision add-on that uses Frigate for object detection"
url: "https://github.com/Direktive-ai/direktive-vision-ha/tree/main/direktive-addon"
arch:
  - aarch64
  - amd64
startup: application
init: false
image: "molefas/direktive-addon"
ports:
  "8554/tcp": 8554 # RTSP
  "8555/tcp": 8555 # WebRTC
  "8555/udp": 8555 # WebRTC
  "1935/tcp": 1935 # RTMP
options:
  api_key: ""
  camera_entity_id: "camera.example_camera"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883

schema:
  api_key: str
  camera_entity_id: str
  mqtt_host: str
  mqtt_port: int  
  mqtt_user: str?
  mqtt_password: password?
  encryption_key: str?
  